### PR TITLE
Issue372 co2

### PR DESCRIPTION
**Pull request by Mathadon**
Pull request once #392 has been accepted
this is for #372

### CODE REVIEW

**Comment by mwetter** [comment]
This is in my view ready to merge. All unit tests work now, and I also integrated it into `Buildings` and all works there too.
I will assign @mlauster for a review as @Mathadon and myself did both significant changes. See also the ticket regarding a backward incompatible change https://github.com/iea-annex60/modelica-annex60/issues/372#issuecomment-174096074.

@thorade : Note that you may need to update your release notes due to the backward incompatible change, see https://github.com/iea-annex60/modelica-annex60/issues/372#issuecomment-174096074

**Comment by Mathadon** [comment]
I'd like to review 360a991 too, hopefully next week!

**Comment by mlauster** [comment]
@Mathadon, are you done with your review?
I will primarly check on usability and general style guides etc.

**Comment by Mathadon** [comment]
@mlauster done, thanks for reminding me!

**Pull request merged**
