### PR TITLE
Issue302 inverse x

### PR DESCRIPTION
**Pull request by mwetter**
This is ready to merge when the fixme's are addressed by @marcusfuchs in https://github.com/iea-annex60/modelica-annex60/issues/301.

This merge contains the reimplementation of the flow functions for #301 and a bug fix for #302 .
The example `Annex60.Utilities.Math.Functions.Examples.InverseXRegularized` has been revised to also plot the 1st and 2nd derivative of `Annex60.Utilities.Math.Functions.inverseXRegularized` which has been newly implemented as the old implementation was only once continuously differentiable.

### CODE REVIEW

**Comment by mwetter** [comment]
@marcusfuchs 
Please hold off with reviewing `inverseXRegularized` as I am working on a more efficient implementation.
The other changes from #301 won't be affect, hence they are ready for review.

**Comment by mwetter** [comment]
@marcusfuchs 
This is ready to be merged. I merged it already to the master of the `Buildings` library in https://github.com/lbl-srg/modelica-buildings/pull/448

Across a few large test models, the simulation time is about 5% to 10% faster.

**Comment by marcusfuchs** [comment]
@mwetter : Github warns of conflicts for this merge. Should I go ahead and resolve these conflicts or is there something wrong with the current version?

**Comment by marcusfuchs** [comment]
I now deleted `FirstDerivative`, `SecondDerivative` and `FlowFunctions` as suggested in #301 and fixed the merge conflicts by using the more recent versions of the 3 files. 
@mwetter: If this is ok with you, I (or you again) can merge this, as from my side all changes appear to be fine.

**Pull request merged**
