### PR TITLE
ConservationEquation.mo now uses semiLinear() for the calculation of energy conservation

### PR DESCRIPTION
**Pull request by Mathadon**
this allows equations to be simplified by Dymola when allowFlowReversal = false

See issue #216 for further motivation

### CODE REVIEW

**Comment by Mathadon** [comment]
Unit tests are ok

**Comment by Mathadon** [comment]
I need this for the #241 branch. Can this be merged soon or shall I merge it into branch ```issue241_speed``` myself?

**Comment by Mathadon** [comment]
Can we have a look at this?

**Comment by mwetter** [comment]
I will review the code today.

**Comment by mwetter** [comment]
@Mathadon : 
Can you revise the numbers in
<h3>
AllowFlowReversal = true
</h3>
<p>
Sizes of nonlinear systems of equations: {7, 21, <b>56</b>}<br/>
Sizes after manipulation of the nonlinear systems: {2, 10, <b>12</b>}
</p>
<h3>
AllowFlowReversal = false
</h3>
<p>
<b>Old implementation</b>
</p>
<p>
Sizes of nonlinear systems of equations: {7, 21, <b>56</b>}<br/>
Sizes after manipulation of the nonlinear systems: {2, 10, <b>12</b>}
</p>
<p>
<b>New implementation</b>
</p>
<p>
Sizes of nonlinear systems of equations: {7, 21, <b>4</b>}<br/>
Sizes after manipulation of the nonlinear systems: {2, 10, <b>1</b>}
</p>

For example, with `allowFlowReversal=false`, I get
```
Sizes after manipulation of the nonlinear systems: {1, 9, 1}
```
with and without your changes to `ConservationEquation.mo`. Hence, for this example that should demonstrate the benefit of using `semiLinear`, I see no difference.


Also, please provide an `.mos` script with `allowFlowReversal=false`, otherwise we will not detect if we revert your changes.

Please first merge your branch with https://github.com/iea-annex60/modelica-annex60/tree/issue216_semiLinConsEq to avoid conflicts.

**Comment by Mathadon** [comment]
Hey Michael,

the problem did indeed disappear after merging https://github.com/iea-annex60/modelica-annex60/tree/issue216_semiLinConsEq  into my branch. This is due to the changed implementation of ```MixingVolume``` that now uses ```Annex60.Fluid.Interfaces.StaticTwoPortConservationEquation``` so it makes sense that changes in ```Annex60.Fluid.Interfaces.ConservationEquation``` no longer have an influence.

I changed the example model by setting ```each vol.allowFlowReversal = true```. This causes ```Annex60.Fluid.Interfaces.ConservationEquation``` to be used again and the issue then reappears.

Note that there seems to be a bug in Dymola when you set ```Evaluate = true```, which I used to do by default. The result then change from
```
Sizes of nonlinear systems of equations: {6, 11, 4}
Sizes after manipulation of the nonlinear systems: {1, 9, 1}
```

into
```
Sizes of nonlinear systems of equations: {7, 21, 4}
Sizes after manipulation of the nonlinear systems: {2, 10, 1}
```
when ```allowFlowReversal=false```. This also causes the documentation to be 'wrong'. I'll fix this.

**Comment by Mathadon** [comment]
Note that it seems a bit dull that I set ```vol.allowFlowReversal = true``` since the whole idea is that Dymola simplifies equations when ```allowFlowReversal=false```. However ```allowFlowReversal``` is still ```false``` in ```res```. Dymola detects that this is the case and therefore the simplification still happens. Note that this 'propagation' of ```m_flow(min=0)``` is not always properly executed and it may depend on how alias variables are chosen. I have submitted a bug report for this at Claytex.

**Pull request merged**
