### PR TITLE
Issue536 corsica

### LINKED ISSUE #536: Flow system examples for Corsica
This issue is to discuss some examples that could be added to the Annex 60 library that further demonstrate the use of options such as 
- energyDynamics
- filteredSpeed
- allowFlowReversal
- from_dp

etc

### PR DESCRIPTION
**Pull request by Mathadon**
@mwetter 
I added unit tests and reference results. I only unit-tested two mass flow rates of the models since the statistics seem the most relevant to me.
This closes #536

### CODE REVIEW

**Comment by Mathadon** [comment]
it seems that `Annex60.Fluid.Examples.FlowSystem.Simplified1` crashes.. can we put such a model in the unit tests?

**Comment by Mathadon** [comment]
Suddenly I get:
```
File "/usr/local/lib/python2.7/dist-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/io/postprocess.py", line 46, in interpolate
    raise ValueError('len(t) = %d but len(y) = %d, they must be equal.' % (len(t), len(y)))
ValueError: len(t) = 101 but len(y) = 11, they must be equal.
```
does this indicate a crash in dymola or is this a bug in buildingspy?

**Comment by Mathadon** [comment]
I fixed it by shortening the simulation duration. This is ready to be merged.

**Comment by mwetter** [comment]
@Mathadon 
Can you please review my latest revisions and if you are fine with them, merge it to the master.

**Pull request merged**
