### PR TITLE
Issue188 heater

### LINKED ISSUE #188: Heater example does no longer work in OpenModelica with new medium
The commit https://github.com/iea-annex60/modelica-annex60/commit/25376251ea98705b3b12fb4ba2e9d875c802e2a8
causes `Annex60.Fluid.HeatExchangers.Examples.Heater_T` to fail with
```
Annex60/Fluid/Interfaces/ConservationEquation.mo:233:7-233:37:writable] Error: Initialization problem is structurally singular, error found sorting equations 
 98: vol.dynBal.medium.p = bou.p;
5: vol.dynBal.medium.p = 101325.0;
 for variables 
 conPI.I.k(18), vol.dynBal.medium.T(108), theCon.G(6)
Error: No system for the symbolic initialization was generated.
```

### PR DESCRIPTION
**Pull request by mwetter**
This closes #188. Now these models:
```
simulate(Annex60.Fluid.HeatExchangers.Examples.AirHeater_T);
simulate(Annex60.Fluid.HeatExchangers.Examples.WaterHeater_T);
simulate(Annex60.Fluid.HeatExchangers.Examples.AirHeater_u);
simulate(Annex60.Fluid.HeatExchangers.Examples.WaterHeater_u);
```
all work in OpenModelica.

### CODE REVIEW

**Comment by mwetter** [comment]
This will also close https://github.com/lbl-srg/modelica-buildings/issues/380

**Comment by marcusfuchs** [comment]
I tested the new models with OM 1.9.3 on Windows and three of them run fine, but I get an error for `AirHeater_u`. Does it run on your system @mwetter?

**Comment by mwetter** [comment]
I used Ubuntu with  OpenModelica 1.9.4~dev-629-g8275b87 (the nightly built).
I made a new branch
https://github.com/iea-annex60/modelica-annex60/tree/issue188_heater_openmodelica_tests
 that contains the two scripts I used to run the four models, using
```
cd modelica-annex60
./testOpenModelica.sh
```
This works fine.

However, I just run `AirHeater_u` in OMEdit, also the nightly build, and get the error below:
---
stdout | OMEditInfo | <p>/tmp/OpenModelica_mwetter/OMEdit/Annex60.Fluid.HeatExchangers.Examples.AirHeater_u -port=34044 -logFormat=xml -override=startTime=0,stopTime=172800,stepSize=345.6,tolerance=1e-05,solver=dassl,outputFormat=mat,variableFilter=.* -r=Annex60.Fluid.HeatExchangers.Examples.AirHeater_u_res.mat -dasslJacobian=coloredNumerical -w -lv=LOG_STATS</p>
stdout | error | <p>Got number 186.000000, expected: 185.000000<br>

stdout | error | <p>Process crashed<br>
Simulation process failed. Exited with code 0.</p>

---
I assume it has something to do with the compilation flags? Maybe @sjoelund  has an idea why the model simulates from the console but not from OMEdit?

**Comment by mwetter** [comment]
@marcusfuchs : I suggest that you go ahead with merging this. `AirHeater_u` works with the above mentioned scripts that use ` +maxMixedDeterminedIndex=4`. In OMEdit with the default setting, it does not work. However, also the old model `Heater_u` on the `master` that uses air as the medium does not work. Hence, there is still one model that does not work in `OMEdit`, but at least we have working test cases with water as the medium.

For `AirHeater_u`, the error message from OpenModelica is still `Got number 186.000000, expected: 185.000000` which I don't quite know what it means.

**Comment by marcusfuchs** [comment]
Alright, everything else looks good, so I'll merge this.

**Pull request merged**
