### PR TITLE
Issue494 optional integrator reset for PID

### PR DESCRIPTION
**Pull request by PMehrfeld**
#494

### CODE REVIEW

**Comment by Mathadon** [comment]
We'll have to check this with @mwetter too, so let us get back to you!

**Comment by PMehrfeld** [comment]
Alright. Thanks a lot!

**Comment by mwetter** [comment]
@PMehrfeld 

I have a few questions/comments to your implementation.

1. Is the integrator anti-windup as implemented in the original controller not sufficient? If you indeed have a case for having to use a reset, then we can certainly add this, but I am asking as I have not yet encountered this need and hence want to avoid adding complexity if there is no need for such a feature.
1. I would rename `resetI` to `reset` as the integrator is anyway the only thing that can be reset, so no need to use `I` in the name.
1. `IntegratorWithReset` should be moved to `Utilities.Math` as it may be useful for other applications, and it is not a controller by itself (and hence should not be in `Controls.Continuous`.
1. Is it really needed to have `intResetValue`? Why would someone use a different value than `xi_start`?
1. To use consistency with other parameter names, please rename `withResetIntegrator` to `use_reset`.
1. The documentation talks about rising edge, but the implementation uses `edge`.
1. The code `when edge(resetIPassThrough.y) then` should be in an `if use_reset` and `use_reset` would need `annoation(Evaluate=true)` so that (hopefully) tools will remove this event if not needed.
1. Examples or validation tests need to be added before it can be merged to the master (we need test for all features to ensure that we don't break what has been tested already).

**Comment by PMehrfeld** [comment]
@mwetter 
Thank you very much for your feedback.

1. The anti-windup feature only drives down the integrator when the boundary limits are reached/exceeded. Even then there is no hard reset to `y_start` (or any other value). Please correct me, if have overlooked something.
Regarding an exemplaric case: For example, a plant/system should be shut down when a certain trigger/boolean becomes true, and when it restarts the integration must start from zero again.
Anyway, the model `IntegratorWithReset` can be very useful in diverse applications.

2. OK -> Done

3. Absolutely!! -> Done

4. This was Filip's suggestion (see #494 ). It might be useful for some people.

5. OK -> Done

6. To my knowledge the `edge()` function means a rising edge. A test proved this. Additionally, a closer look to the block `Modelica.Blocks.MathBoolean.RisingEdge` says: 
```
block RisingEdge
  "Output y is true, if the input u has a rising edge, otherwise it is false (y = edge(u))"
[...]
equation 
  y = edge(u);
end RisingEdge;
```

7. OK -> Done

8. OK -> Done with `Controls.Continuous.Examples.LimPIDWithReset` and `Utilities.Math.Examples.IntegratorWithReset`.
The remaining applications where `LimPID` is used should still work, as default parameter values disable the integrator reset.

**Comment by mwetter** [comment]
@PMehrfeld Thanks for the changes. I will review but it may take a bit longer due to travel this and next week. I merged your changes to https://github.com/iea-annex60/modelica-annex60/tree/issue494_resetIntPID and will commit my revision to this branch.

**Comment by PMehrfeld** [comment]
@mwetter I have comitted into my fork the discussed changes:
1. `LimPID` output is set to 0 if boolean input `reset `has a rising edge.
2. I implemented the Annex60 types `Annex60.BoundaryConditions.Types.DataSource.Input` and `.Parameter` in the model `IntegratorWithReset`. Additionally, I use the `_internal ` variables.

I also revised the 2 examples and added scripts to `Annex60\Resources\Scripts\Dymola\...`.
Unfortunately, I could not manage to get the python script `runUnitTests.py` work properly.

Can I do any further work or does this satisfy your requirements?

**Pull request closed without merging**
