### PR TITLE
Issue353 add carnot y

### PR DESCRIPTION
**Pull request by damienpicard**
Add carnot machine to master.

### CODE REVIEW

**Comment by mwetter** [comment]
@damienpicard : I added Carnot heat pumps and chillers that take the leaving water temperature or the compressor speed as an input signal. I started with your models, and then refactored them as we have now 4 models that share similar functionalities. I also added many validation tests.
All unit tests work fine. Can you please review and then merge to the master.

This will close #353

**Comment by damienpicard** [comment]
@mwetter `Annex60.Fluid.Chillers.BaseClasses.PartialCarnot_y` and  `Annex60.Fluid.Chillers.BaseClasses.PartialCarnot_T` are very similar but due to the fact that the first extend from `Interfaces.FourPortHeatMassExchanger` and the other not oblige you to have quite some code duplication.

I wonder if it would not make more sense to use the implementation of `Annex60.Fluid.Chillers.BaseClasses.PartialCarnot_T` for both models and redeclaring `con` with `HeatExchangers.HeaterCooler_u`? If not, making an extra partial with only the parameters of `Interfaces.FourPortHeatMassExchanger` could also improve the current code.

**Comment by damienpicard** [comment]
otherwise, the models are good.

**Comment by mwetter** [comment]
@damienpicard Thanks for pointing this out. I will try to
 - [ ] use `Annex60.Fluid.Chillers.BaseClasses.PartialCarnot_T` as the base class for both models.

I think this should yield a clearer implementation.

**Comment by mwetter** [comment]
@damienpicard 
I refactored the heat pumps and chiller model so that there is less code duplication. The implementation actually got simpler. Thanks for this comment.

Can you please review https://github.com/iea-annex60/modelica-annex60/commit/2a1e8c147e2f35a8c8a3e27cebc6004232e26c58 so we can merge it to the master branch?

**Pull request merged**
