### PR TITLE
Remove default and dummy annotations

### PR DESCRIPTION
**Pull request by tbeu**
* fix "No newline at end of file"
 * remove trailing white spaces
 * remove dummy graphics annotation
 * remove __Dymola_experimentSetupOutput annotation
 * remove color = {0,0,0}
 * remove initialScale = 0.1
 * remove origin = {0,0}
 * remove rotation = 0
 * remove smooth = Smooth.None
 * remove visible = true

### CODE REVIEW

**Comment by mwetter** [comment]
@tbeu 
Thanks for the pull request. As we cannot see the diffs in github (too many changes) and because a manual merge fails (due to curl redirecting), could you please issue this pull request against the development branch https://github.com/iea-annex60/modelica-annex60/tree/issue324_defaultAnnotations
This will allow us to test and review the changes before we merge it to the master.
Thanks.

**Comment by thorade** [comment]
I guess he would then have to rerun ttws, because the repository is already deleted (on github, don't know about the local copy).
Ignoring whitespace in the diff (by appending `?w=1`) seems to show everything:
https://github.com/iea-annex60/modelica-annex60/commit/5a10aed76fba63fbfdf1c8c4ed3443013d191fee?w=1
There is still an error message, but it looks like all files are shown.

**Comment by tbeu** [comment]
I also deleted the local copy (too early as I now see). Can't you merge it to any other branch than the master?

**Comment by tbeu** [comment]
OK, you can continue in #324 and #325.

**Pull request closed without merging**
