### PR TITLE
Issue646 number of requests

### PR DESCRIPTION
**Pull request by tsnouidui**
@mwetter I added a validation package for the `Diagnostics` models and also increase the tolerance for the `MixingVolume` example for JModelica verification. Once This is merged, we should merge this to the `Buildings` library master branch and then merge the `master` to the `Buildings` verification branch.

### CODE REVIEW

**Comment by mwetter** [comment]
This is ready to merge to the Annex 60 `master` after the official release of the `Annex60` library.

@tsnouidui I will merge it to the `Buildings` master.

**Comment by tsnouidui** [comment]
@mwetter why is following unit test result not on the `Buildings` master branch? `Annex60_Utilities_Diagnostics_Validation_CheckEquality.txt`?

**Comment by mwetter** [comment]
@tsnouidui It now is on the Buildings master.

**Comment by tsnouidui** [comment]
Thanks! Will wait for official release of `Annex60` prior to merging this to the `Annex60` master branch then. I did merge this on the verification branch for JModelica to solve issues associated with the changes.

**Pull request merged**
