### PR TITLE
Issue489 weather fmu

### PR DESCRIPTION
**Pull request by tsnouidui**
This addresses #489.

### CODE REVIEW

**Comment by tsnouidui** [comment]
@mwetter Line length has been reduced.

**Comment by mwetter** [comment]
This does not yet pass the `Buildings` regression tests and hence should not be merged: https://github.com/lbl-srg/modelica-buildings/pull/540#issuecomment-236203641

**Comment by mwetter** [comment]
@marcusfuchs : Can you please review and merge? This now passes the tests also for the `Buildings` library and is integrated in `Buildings:master`.

**Comment by marcusfuchs** [comment]
@mwetter : Looks good and can be merged from my point of view. I just changed one instance of "uri" in a description string to "URI", as all other references in the documentation and descriptions also used "URI". In addition, my text editor removed a few trailing whitespaces. If that is fine with you, either you or I could merge this, otherwise I could also revert the whitespace changes.

**Comment by mwetter** [comment]
@marcusfuchs : Thanks for the review and changes, I will merge it.

**Pull request merged**
