### PR TITLE
fixed bug in ReaderTMY3 that caused large HDirNor at night when using…

### LINKED ISSUE #608: HDirNor in weaBus if HSource is set to connector
If you set `HSo` to `Annex60.BoundaryConditions.Types.RadiationDataSource.Input_HGloHor_HDifHor` in `ReaderTMY3` and give `HDifHor_in` and `HGloHor_in` via connectors, you get strange results for `HDirNor`.

### PR DESCRIPTION
**Pull request by Mathadon**
… custom inputs

this closes #608

### CODE REVIEW

**Comment by Mathadon** [comment]
I just came across a case where this issue resulted in a temperature spike of 1K during the evening because 1MW of thermal power was being injected for a short duration. The proposed fix solved this.

**Comment by tsnouidui** [comment]
@Mathadon you seem to have been working on this in parallel ;-). The fix seems to be the same (https://github.com/iea-annex60/modelica-annex60/pull/625). I also added a unittest to exercise such a case. @mlauster/ @mwetter  You will have to pick one of the two implementations to avoid merge conflicts afterwards.

**Comment by mwetter** [comment]
@Mathadon I reviewed https://github.com/iea-annex60/modelica-annex60/pull/625 as this contains a test that reproduced the problem. I plan to close this when I merge https://github.com/iea-annex60/modelica-annex60/pull/625
Please let me know if you still need your fix.

**Comment by mwetter** [comment]
@Mathadon 
I close this and delete the development branch as I think this is addressed with https://github.com/iea-annex60/modelica-annex60/pull/625

**Pull request closed without merging**
